[engine.logger]
path = '/tmp/'
name = 'Vixel'

[game.window]
title = "Vixel"
resolution = { width = 1920, height = 1080 }
mode = "windowed" # windowed | windowed_borderless | exclusive_full_screen | boderless_full_screen
monitor = 2 
