name: CMake on multiple platforms

on:
  push:
    branches: ["main", "trunk"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            preset: windows
          - os: ubuntu-latest
            c_compiler: gcc
            preset: linux
          - os: ubuntu-latest
            c_compiler: clang
            preset: linux
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    # Usar contenedores solo para Linux

    container:
      image: ${{ matrix.os == 'ubuntu-latest' && matrix.c_compiler == 'gcc' && 'gcc:15.2' || matrix.os == 'ubuntu-latest' && matrix.c_compiler == 'clang' && 'tuxmake/clang-20' || '' }}
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Install Conan
        if: runner.os == 'Linux' || runner.os == 'Windows'
        run: |
          python3 -m pip install --upgrade pip
          pip install conan
          conan profile detect

      - name: Set reusable strings
        id: strings

        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Release Workflow
        run: cmake --workflow ${{ matrix.build_type }}-${{ matrix.preset }}-${{ matrix.c_compiler }}
